version: '3.7'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: python manage.py
    volumes:
      - /usr/src/app/
    env_file: 
      - ./.env.prod
  nginx:
    build: 
      context: ./services/nginx
      dockerfile: Dockerfile.prod
    ports:
      - 1337:80
    depends_on:
      - web
    