version: '3.7'

services:
  panel:
    build:
      context: ./services/panel
      dockerfile: Dockerfile.prod
    command: panel serve terrain-corrector/app.py --port=5100 --allow-websocket-origin='cstern.io' --prefix='/terra-param/' --use-xheaders
    volumes:
      - /usr/src/app/
    expose:
      - 5100
    env_file: 
      - ./.env.prod

  flask:
    build: ./services/flask
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - /usr/src/app/
    expose:
      - 5000
    env_file:
      - ./.env.prod
  
  nginx:
    build: 
      context: ./services/nginx
      dockerfile: Dockerfile.secure
    ports:
      - 80:80
      - 443:443
    depends_on:
      - panel
      - flask
#==commenting out everything below this line makes it run w/out certbot
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - /etc/ssl/certs

  #certbot:
  #  container_name: certbot
  #  image: certbot/certbot
  #  volumes:
  #    - web-root:/var/www/html
  #    - certbot-etc:/etc/letsencrypt
  #    - certbot-var:/var/lib/letsencrypt
  #  depends_on:
  #    - nginx
  #  command: certonly --webroot --webroot-path=/var/www/html --email charlesisaacstern@gmail.com --agree-tos --no-eff-email --force-renewal -d cstern.io  -d www.cstern.io

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/sammy/
      o: bind
  