version: '3.7'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.dev
    command: python manage.py
    volumes:
      - /usr/src/app/
    ports:
      - 5006:5006
    env_file: 
      - ./.env.dev
    